// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQBLKE9ImbnbTwgRv6VZ5zyvs6nB8aM_U',
    appId: '1:308514911111:web:da19780e43ba788c671922',
    messagingSenderId: '308514911111',
    projectId: 'movie-rent',
    authDomain: 'movie-rent.firebaseapp.com',
    storageBucket: 'movie-rent.firebasestorage.app',
    measurementId: 'G-8YMP9SF6C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHv4daw_DfKVq9HZpRtruHiFxwfvpDoo',
    appId: '1:308514911111:android:fb4ea548110912fc671922',
    messagingSenderId: '308514911111',
    projectId: 'movie-rent',
    storageBucket: 'movie-rent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo7fA3tUvD36AnQnlFFyGu0JbSWAnfJpM',
    appId: '1:308514911111:ios:1499c0f1a8df51a1671922',
    messagingSenderId: '308514911111',
    projectId: 'movie-rent',
    storageBucket: 'movie-rent.firebasestorage.app',
    iosBundleId: 'com.example.movieRent',
  );
}
